#!/bin/bash
chmod -R 755 /usr/bin/root
cd "$(dirname "$0")"  
echo "TS-KERNEL Linux Technology Has Been Installed, Have fun Making TS-DISTRO Distros On Linux!"
cd ..
chmod +x DEBIAN/postinst
chmod 755 postinst